version: 2
jobs:
  build:
    working_directory: ~/lakoo-text-purifier-c
    docker:
      - image: aludirk/cpp-dev:4
    steps:
      - checkout
      - run:
          name: Sync Submodule
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build Libraries
          command: |
            ./autogen.sh
            ./configure --enable-doxygen
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              mkdir html
              cd html
              git clone https://github.com/lakoo/text_purifier_c.git .
              git checkout origin/gh-pages -b gh-pages
              git branch -d master
              cd ..
            fi
            make
      - run:
          name: Run Test
          command: |
            make check
            cat test/cppcheck.sh.log
            cat test/test.log
            cat test/valgrind.sh.log
      - deploy:
          name: Deploy
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              cd html
              git add .
              if ! git diff-index --quiet HEAD --; then
                git -c user.name="${CIRCLE_USERNAME}" -c user.email="\<\>" commit -m "GitHub Pages"
                git push origin gh-pages
              fi
            fi
